# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/d/compile/jerryscript-2.3.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/d/compile/jerryscript-2.3.0/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/d/compile/jerryscript-2.3.0/build/CMakeFiles /cygdrive/d/compile/jerryscript-2.3.0/build/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/d/compile/jerryscript-2.3.0/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate-single-source

# Build rule for target.
generate-single-source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate-single-source
.PHONY : generate-single-source

# fast build rule for target.
generate-single-source/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate-single-source.dir/build.make CMakeFiles/generate-single-source.dir/build
.PHONY : generate-single-source/fast

#=============================================================================
# Target rules for targets named jerry-libm

# Build rule for target.
jerry-libm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jerry-libm
.PHONY : jerry-libm

# fast build rule for target.
jerry-libm/fast:
	$(MAKE) $(MAKESILENT) -f jerry-libm/CMakeFiles/jerry-libm.dir/build.make jerry-libm/CMakeFiles/jerry-libm.dir/build
.PHONY : jerry-libm/fast

#=============================================================================
# Target rules for targets named jerry-core

# Build rule for target.
jerry-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jerry-core
.PHONY : jerry-core

# fast build rule for target.
jerry-core/fast:
	$(MAKE) $(MAKESILENT) -f jerry-core/CMakeFiles/jerry-core.dir/build.make jerry-core/CMakeFiles/jerry-core.dir/build
.PHONY : jerry-core/fast

#=============================================================================
# Target rules for targets named jerry-ext

# Build rule for target.
jerry-ext: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jerry-ext
.PHONY : jerry-ext

# fast build rule for target.
jerry-ext/fast:
	$(MAKE) $(MAKESILENT) -f jerry-ext/CMakeFiles/jerry-ext.dir/build.make jerry-ext/CMakeFiles/jerry-ext.dir/build
.PHONY : jerry-ext/fast

#=============================================================================
# Target rules for targets named jerry-port-default-minimal

# Build rule for target.
jerry-port-default-minimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jerry-port-default-minimal
.PHONY : jerry-port-default-minimal

# fast build rule for target.
jerry-port-default-minimal/fast:
	$(MAKE) $(MAKESILENT) -f jerry-port/default/CMakeFiles/jerry-port-default-minimal.dir/build.make jerry-port/default/CMakeFiles/jerry-port-default-minimal.dir/build
.PHONY : jerry-port-default-minimal/fast

#=============================================================================
# Target rules for targets named jerry-port-default

# Build rule for target.
jerry-port-default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jerry-port-default
.PHONY : jerry-port-default

# fast build rule for target.
jerry-port-default/fast:
	$(MAKE) $(MAKESILENT) -f jerry-port/default/CMakeFiles/jerry-port-default.dir/build.make jerry-port/default/CMakeFiles/jerry-port-default.dir/build
.PHONY : jerry-port-default/fast

#=============================================================================
# Target rules for targets named jerry

# Build rule for target.
jerry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jerry
.PHONY : jerry

# fast build rule for target.
jerry/fast:
	$(MAKE) $(MAKESILENT) -f jerry-main/CMakeFiles/jerry.dir/build.make jerry-main/CMakeFiles/jerry.dir/build
.PHONY : jerry/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... generate-single-source"
	@echo "... jerry"
	@echo "... jerry-core"
	@echo "... jerry-ext"
	@echo "... jerry-libm"
	@echo "... jerry-port-default"
	@echo "... jerry-port-default-minimal"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

